DELETE http://localhost:8080/events/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQ0NTU2NzUzLCJ1c2VySWQiOjJ9.POn7FXVGRyd9AhMy1FGtKInJIHpZKGqzARUIn1cuHkU