PUT http://localhost:8080/events/3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQ0NTU3MDMxLCJ1c2VySWQiOjJ9.lO52vE_B7SNbv0LwzWVvgtg4aCFv41jqyhq5Bcl4Eio

{
    "name": "Updated test event",
    "description": "A test event",
    "location": "Test location (updated)",
    "datetime": "2025-01-01T15:30:00.000Z"
}